#!/usr/bin/env ruby
require 'yaml'
require_relative 'populate'

validator_config = YAML.load_file(ARGV.shift)
populated_validator_config = populate(validator_config, ENV)
YAML.dump(populated_validator_config, STDOUT)
